version: '3.4'

services:
    dtsocket:      
      container_name: DateTimeSocket
      build:
        network: host
        context: ./
      restart: always
      ports:
          - target: 80
            published: 8080
            protocol: tcp
            mode: host