version: '3.4'

services:
    dtsocket:
      network_mode: host
      container_name: DateTimeSocket
      build:
        network: host
        context: ./
      restart: always
      ports:
          - 4333:4333
            